
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace ePassport {


    [ASN1PreparedElement]
    [ASN1Sequence(Name = "AttributeCertificateV1", IsSet = false)]
    public class AttributeCertificateV1 : IASN1PreparedElement 
    {
        
        private AttributeCertificateInfoV1 acInfo_;
        
		[ASN1Element(Name = "acInfo", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public AttributeCertificateInfoV1 AcInfo
        {
            get { return acInfo_; }
            set { acInfo_ = value;  }
        }
  
        private AlgorithmIdentifier signatureAlgorithm_;
        
		[ASN1Element(Name = "signatureAlgorithm", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public AlgorithmIdentifier SignatureAlgorithm
        {
            get { return signatureAlgorithm_; }
            set { signatureAlgorithm_ = value;  }
        }
  
        private BitString signature_;
        [ASN1BitString( Name = "" )]
    
		[ASN1Element(Name = "signature", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public BitString Signature
        {
            get { return signature_; }
            set { signature_ = value;  }
        }
  

        public void initWithDefaults() 
        {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(AttributeCertificateV1));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
