
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace ePassport {


    [ASN1PreparedElement]
    [ASN1Sequence(Name = "CscaMasterList", IsSet = false)]
    public class CscaMasterList : IASN1PreparedElement 
    {
        
        private CscaMasterListVersion version_;
        
		[ASN1Element(Name = "version", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public CscaMasterListVersion Version
        {
            get { return version_; }
            set { version_ = value;  }
        }
  
        private System.Collections.Generic.ICollection<Certificate> certList_;
        
		[ASN1SequenceOf(Name = "certList", IsSetOf = true)]
    
		[ASN1Element(Name = "certList", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public System.Collections.Generic.ICollection<Certificate> CertList
        {
            get { return certList_; }
            set { certList_ = value;  }
        }
  

        public void initWithDefaults() 
        {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(CscaMasterList));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
