
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace ePassport {


    [ASN1PreparedElement]
    [ASN1Sequence(Name = "DataGroupHash", IsSet = false)]
    public class DataGroupHash : IASN1PreparedElement 
    {
        
        private DataGroupNumber dataGroupNumber_;
        
		[ASN1Element(Name = "dataGroupNumber", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public DataGroupNumber DataGroupNumber
        {
            get { return dataGroupNumber_; }
            set { dataGroupNumber_ = value;  }
        }
  
        private byte[] dataGroupHashValue_;
        [ASN1OctetString( Name = "" )]
    
		[ASN1Element(Name = "dataGroupHashValue", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public byte[] DataGroupHashValue
        {
            get { return dataGroupHashValue_; }
            set { dataGroupHashValue_ = value;  }
        }
  

        public void initWithDefaults() 
        {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(DataGroupHash));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
