
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace ePassport {


    [ASN1PreparedElement]
    [ASN1Sequence(Name = "LDSVersionInfo", IsSet = false)]
    public class LDSVersionInfo : IASN1PreparedElement 
    {
        
        private string ldsVersion_;
        
		[ASN1String(Name = "", StringType = UniversalTags.PrintableString, IsUCS = false)]
		[ASN1Element(Name = "ldsVersion", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public string LdsVersion
        {
            get { return ldsVersion_; }
            set { ldsVersion_ = value;  }
        }
  
        private string unicodeVersion_;
        
		[ASN1String(Name = "", StringType = UniversalTags.PrintableString, IsUCS = false)]
		[ASN1Element(Name = "unicodeVersion", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public string UnicodeVersion
        {
            get { return unicodeVersion_; }
            set { unicodeVersion_ = value;  }
        }
  

        public void initWithDefaults() 
        {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(LDSVersionInfo));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
