
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace ePassport {


    [ASN1PreparedElement]
    [ASN1Choice(Name = "CertificateChoices")]
    public class CertificateChoices : IASN1PreparedElement 
    {
        
        private Certificate certificate_;
        private bool  certificate_selected = false;

        
		[ASN1Element(Name = "certificate", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public Certificate Certificate
        {
            get { return certificate_; }
            set { selectCertificate(value); }
        }
  
        private ExtendedCertificate extendedCertificate_;
        private bool  extendedCertificate_selected = false;

        
		[ASN1Element(Name = "extendedCertificate", IsOptional = false, HasTag = true, Tag = 0, HasDefaultValue = false)]
        public ExtendedCertificate ExtendedCertificate
        {
            get { return extendedCertificate_; }
            set { selectExtendedCertificate(value); }
        }
  
        private AttributeCertificateV1 v1AttrCert_;
        private bool  v1AttrCert_selected = false;

        
		[ASN1Element(Name = "v1AttrCert", IsOptional = false, HasTag = true, Tag = 1, HasDefaultValue = false)]
        public AttributeCertificateV1 V1AttrCert
        {
            get { return v1AttrCert_; }
            set { selectV1AttrCert(value); }
        }
  
        private AttributeCertificateV2 v2AttrCert_;
        private bool  v2AttrCert_selected = false;

        
		[ASN1Element(Name = "v2AttrCert", IsOptional = false, HasTag = true, Tag = 2, HasDefaultValue = false)]
        public AttributeCertificateV2 V2AttrCert
        {
            get { return v2AttrCert_; }
            set { selectV2AttrCert(value); }
        }
  
        private OtherCertificateFormat other_;
        private bool  other_selected = false;

        
		[ASN1Element(Name = "other", IsOptional = false, HasTag = true, Tag = 3, HasDefaultValue = false)]
        public OtherCertificateFormat Other
        {
            get { return other_; }
            set { selectOther(value); }
        }
  
        public bool isCertificateSelected()
        {
            return this.certificate_selected;
        }

        

        public void selectCertificate (Certificate val) 
        {
            this.certificate_ = val;
            this.certificate_selected = true;
            
            this.extendedCertificate_selected = false;
            
            this.v1AttrCert_selected = false;
            
            this.v2AttrCert_selected = false;
            
            this.other_selected = false;
            
        }
  
        public bool isExtendedCertificateSelected()
        {
            return this.extendedCertificate_selected;
        }

        

        public void selectExtendedCertificate (ExtendedCertificate val) 
        {
            this.extendedCertificate_ = val;
            this.extendedCertificate_selected = true;
            
            this.certificate_selected = false;
            
            this.v1AttrCert_selected = false;
            
            this.v2AttrCert_selected = false;
            
            this.other_selected = false;
            
        }
  
        public bool isV1AttrCertSelected()
        {
            return this.v1AttrCert_selected;
        }

        

        public void selectV1AttrCert (AttributeCertificateV1 val) 
        {
            this.v1AttrCert_ = val;
            this.v1AttrCert_selected = true;
            
            this.certificate_selected = false;
            
            this.extendedCertificate_selected = false;
            
            this.v2AttrCert_selected = false;
            
            this.other_selected = false;
            
        }
  
        public bool isV2AttrCertSelected()
        {
            return this.v2AttrCert_selected;
        }

        

        public void selectV2AttrCert (AttributeCertificateV2 val) 
        {
            this.v2AttrCert_ = val;
            this.v2AttrCert_selected = true;
            
            this.certificate_selected = false;
            
            this.extendedCertificate_selected = false;
            
            this.v1AttrCert_selected = false;
            
            this.other_selected = false;
            
        }
  
        public bool isOtherSelected()
        {
            return this.other_selected;
        }

        

        public void selectOther (OtherCertificateFormat val) 
        {
            this.other_ = val;
            this.other_selected = true;
            
            this.certificate_selected = false;
            
            this.extendedCertificate_selected = false;
            
            this.v1AttrCert_selected = false;
            
            this.v2AttrCert_selected = false;
            
        }
  

        public void initWithDefaults()
        {
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(CertificateChoices));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
