
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace ePassport {


    [ASN1PreparedElement]
    [ASN1Sequence(Name = "EncryptedContentInfo", IsSet = false)]
    public class EncryptedContentInfo : IASN1PreparedElement 
    {
        
        private ContentType contentType_;
        
		[ASN1Element(Name = "contentType", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public ContentType ContentType
        {
            get { return contentType_; }
            set { contentType_ = value;  }
        }
  
        private ContentEncryptionAlgorithmIdentifier contentEncryptionAlgorithm_;
        
		[ASN1Element(Name = "contentEncryptionAlgorithm", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public ContentEncryptionAlgorithmIdentifier ContentEncryptionAlgorithm
        {
            get { return contentEncryptionAlgorithm_; }
            set { contentEncryptionAlgorithm_ = value;  }
        }
  
        private EncryptedContent encryptedContent_;
        
        private bool  encryptedContent_present = false;
        
		[ASN1Element(Name = "encryptedContent", IsOptional = true, HasTag = true, Tag = 0, HasDefaultValue = false)]
        public EncryptedContent EncryptedContent
        {
            get { return encryptedContent_; }
            set { encryptedContent_ = value; encryptedContent_present = true;  }
        }
  
        public bool isEncryptedContentPresent()
        {
            return this.encryptedContent_present == true;
        }
        

        public void initWithDefaults() 
        {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(EncryptedContentInfo));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
