
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace ePassport {


    [ASN1PreparedElement]
    [ASN1Sequence(Name = "ExtendedCertificateInfo", IsSet = false)]
    public class ExtendedCertificateInfo : IASN1PreparedElement 
    {
        
        private CMSVersion version_;
        
		[ASN1Element(Name = "version", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public CMSVersion Version
        {
            get { return version_; }
            set { version_ = value;  }
        }
  
        private Certificate certificate_;
        
		[ASN1Element(Name = "certificate", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public Certificate Certificate
        {
            get { return certificate_; }
            set { certificate_ = value;  }
        }
  
        private UnauthAttributes attributes_;
        
		[ASN1Element(Name = "attributes", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public UnauthAttributes Attributes
        {
            get { return attributes_; }
            set { attributes_ = value;  }
        }
  

        public void initWithDefaults() 
        {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(ExtendedCertificateInfo));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
