
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace ePassport {


    [ASN1PreparedElement]
    [ASN1Sequence(Name = "OtherCertificateFormat", IsSet = false)]
    public class OtherCertificateFormat : IASN1PreparedElement 
    {
        
        private ObjectIdentifier otherCertFormat_;
        [ASN1ObjectIdentifier( Name = "" )]
    
		[ASN1Element(Name = "otherCertFormat", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public ObjectIdentifier OtherCertFormat
        {
            get { return otherCertFormat_; }
            set { otherCertFormat_ = value;  }
        }
  
        private byte[] otherCert_;
        [ASN1Any( Name = "" )]
    
		[ASN1Element(Name = "otherCert", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public byte[] OtherCert
        {
            get { return otherCert_; }
            set { otherCert_ = value;  }
        }
  

        public void initWithDefaults() 
        {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(OtherCertificateFormat));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
