
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace ePassport {


    [ASN1PreparedElement]
    [ASN1Sequence(Name = "OtherRecipientInfo", IsSet = false)]
    public class OtherRecipientInfo : IASN1PreparedElement 
    {
        
        private ObjectIdentifier oriType_;
        [ASN1ObjectIdentifier( Name = "" )]
    
		[ASN1Element(Name = "oriType", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public ObjectIdentifier OriType
        {
            get { return oriType_; }
            set { oriType_ = value;  }
        }
  
        private byte[] oriValue_;
        [ASN1Any( Name = "" )]
    
		[ASN1Element(Name = "oriValue", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public byte[] OriValue
        {
            get { return oriValue_; }
            set { oriValue_ = value;  }
        }
  

        public void initWithDefaults() 
        {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(OtherRecipientInfo));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
