
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace ePassport {


    [ASN1PreparedElement]
    [ASN1Sequence(Name = "OtherKeyAttribute", IsSet = false)]
    public class OtherKeyAttribute : IASN1PreparedElement 
    {
        
        private ObjectIdentifier keyAttrId_;
        [ASN1ObjectIdentifier( Name = "" )]
    
		[ASN1Element(Name = "keyAttrId", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public ObjectIdentifier KeyAttrId
        {
            get { return keyAttrId_; }
            set { keyAttrId_ = value;  }
        }
  
        private byte[] keyAttr_;
        
        private bool  keyAttr_present = false;
        [ASN1Any( Name = "" )]
    
		[ASN1Element(Name = "keyAttr", IsOptional = true, HasTag = false, HasDefaultValue = false)]
        public byte[] KeyAttr
        {
            get { return keyAttr_; }
            set { keyAttr_ = value; keyAttr_present = true;  }
        }
  
        public bool isKeyAttrPresent()
        {
            return this.keyAttr_present == true;
        }
        

        public void initWithDefaults() 
        {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(OtherKeyAttribute));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
