
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace ePassport {


    [ASN1PreparedElement]
    [ASN1Choice(Name = "RecipientInfo")]
    public class RecipientInfo : IASN1PreparedElement 
    {
        
        private KeyTransRecipientInfo ktri_;
        private bool  ktri_selected = false;

        
		[ASN1Element(Name = "ktri", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public KeyTransRecipientInfo Ktri
        {
            get { return ktri_; }
            set { selectKtri(value); }
        }
  
        private KeyAgreeRecipientInfo kari_;
        private bool  kari_selected = false;

        
		[ASN1Element(Name = "kari", IsOptional = false, HasTag = true, Tag = 1, HasDefaultValue = false)]
        public KeyAgreeRecipientInfo Kari
        {
            get { return kari_; }
            set { selectKari(value); }
        }
  
        private KEKRecipientInfo kekri_;
        private bool  kekri_selected = false;

        
		[ASN1Element(Name = "kekri", IsOptional = false, HasTag = true, Tag = 2, HasDefaultValue = false)]
        public KEKRecipientInfo Kekri
        {
            get { return kekri_; }
            set { selectKekri(value); }
        }
  
        private PasswordRecipientInfo pwri_;
        private bool  pwri_selected = false;

        
		[ASN1Element(Name = "pwri", IsOptional = false, HasTag = true, Tag = 3, HasDefaultValue = false)]
        public PasswordRecipientInfo Pwri
        {
            get { return pwri_; }
            set { selectPwri(value); }
        }
  
        private OtherRecipientInfo ori_;
        private bool  ori_selected = false;

        
		[ASN1Element(Name = "ori", IsOptional = false, HasTag = true, Tag = 4, HasDefaultValue = false)]
        public OtherRecipientInfo Ori
        {
            get { return ori_; }
            set { selectOri(value); }
        }
  
        public bool isKtriSelected()
        {
            return this.ktri_selected;
        }

        

        public void selectKtri (KeyTransRecipientInfo val) 
        {
            this.ktri_ = val;
            this.ktri_selected = true;
            
            this.kari_selected = false;
            
            this.kekri_selected = false;
            
            this.pwri_selected = false;
            
            this.ori_selected = false;
            
        }
  
        public bool isKariSelected()
        {
            return this.kari_selected;
        }

        

        public void selectKari (KeyAgreeRecipientInfo val) 
        {
            this.kari_ = val;
            this.kari_selected = true;
            
            this.ktri_selected = false;
            
            this.kekri_selected = false;
            
            this.pwri_selected = false;
            
            this.ori_selected = false;
            
        }
  
        public bool isKekriSelected()
        {
            return this.kekri_selected;
        }

        

        public void selectKekri (KEKRecipientInfo val) 
        {
            this.kekri_ = val;
            this.kekri_selected = true;
            
            this.ktri_selected = false;
            
            this.kari_selected = false;
            
            this.pwri_selected = false;
            
            this.ori_selected = false;
            
        }
  
        public bool isPwriSelected()
        {
            return this.pwri_selected;
        }

        

        public void selectPwri (PasswordRecipientInfo val) 
        {
            this.pwri_ = val;
            this.pwri_selected = true;
            
            this.ktri_selected = false;
            
            this.kari_selected = false;
            
            this.kekri_selected = false;
            
            this.ori_selected = false;
            
        }
  
        public bool isOriSelected()
        {
            return this.ori_selected;
        }

        

        public void selectOri (OtherRecipientInfo val) 
        {
            this.ori_ = val;
            this.ori_selected = true;
            
            this.ktri_selected = false;
            
            this.kari_selected = false;
            
            this.kekri_selected = false;
            
            this.pwri_selected = false;
            
        }
  

        public void initWithDefaults()
        {
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(RecipientInfo));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
