
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace ePassport {


    [ASN1PreparedElement]
    [ASN1BoxedType(Name = "DGSOD")]
    public class DGSOD: IASN1PreparedElement 
    {

        private DGSODSequenceType val;

        
    [ASN1PreparedElement]
    [ASN1Sequence(Name = "DGSOD", IsSet = false)]
    public class DGSODSequenceType : IASN1PreparedElement
    {
        
        private ContentInfo sod_;
        
		[ASN1Element(Name = "sod", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public ContentInfo Sod
        {
            get { return sod_; }
            set { sod_ = value;  }
        }
  
        
        public void initWithDefaults() 
        {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(DGSODSequenceType));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }
    }
                
		[ASN1Element(Name = "DGSOD", IsOptional = false, HasTag = true, Tag = 23, TagClass = TagClasses.Application, HasDefaultValue = false)]
        public DGSODSequenceType Value
        {
            get { return val; }
            
            set { val = value; }
            
        }

        
        
        public DGSOD ()
        {
        }

        public void initWithDefaults()
        {
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(DGSOD));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
