
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace ePassport {


    [ASN1PreparedElement]
    [ASN1Sequence(Name = "Attribute", IsSet = false)]
    public class Attribute : IASN1PreparedElement 
    {
        
        private AttributeType type_;
        
		[ASN1Element(Name = "type", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public AttributeType Type
        {
            get { return type_; }
            set { type_ = value;  }
        }
  
        private System.Collections.Generic.ICollection<byte[]> values_;
        [ASN1Any( Name = "" )]
    
		[ASN1SequenceOf(Name = "values", IsSetOf = true)]
    
		[ASN1Element(Name = "values", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public System.Collections.Generic.ICollection<byte[]> Values
        {
            get { return values_; }
            set { values_ = value;  }
        }
  

        public void initWithDefaults() 
        {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(Attribute));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
