
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace ePassport {


    [ASN1PreparedElement]
    [ASN1BoxedType(Name = "CountryName")]
    public class CountryName: IASN1PreparedElement 
    {

        private CountryNameChoiceType val;

        

    [ASN1PreparedElement]
    [ASN1Choice(Name = "CountryName")]
    public class CountryNameChoiceType : IASN1PreparedElement  
    {
        
        private string x121_dcc_code_;
        private bool  x121_dcc_code_selected = false;

        
		[ASN1String(Name = "", StringType = UniversalTags.NumericString, IsUCS = false)]
		[ASN1Element(Name = "x121-dcc-code", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public string X121_dcc_code
        {
            get { return x121_dcc_code_; }
            set { selectX121_dcc_code(value); }
        }
  
        private string iso_3166_alpha2_code_;
        private bool  iso_3166_alpha2_code_selected = false;

        
		[ASN1String(Name = "", StringType = UniversalTags.PrintableString, IsUCS = false)]
		[ASN1Element(Name = "iso-3166-alpha2-code", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public string Iso_3166_alpha2_code
        {
            get { return iso_3166_alpha2_code_; }
            set { selectIso_3166_alpha2_code(value); }
        }
  
        public bool isX121_dcc_codeSelected()
        {
            return this.x121_dcc_code_selected;
        }

        

        public void selectX121_dcc_code (string val) 
        {
            this.x121_dcc_code_ = val;
            this.x121_dcc_code_selected = true;
            
            this.x121_dcc_code_selected = false;
            
            this.iso_3166_alpha2_code_selected = false;
            
        }
  
        public bool isIso_3166_alpha2_codeSelected()
        {
            return this.iso_3166_alpha2_code_selected;
        }

        

        public void selectIso_3166_alpha2_code (string val) 
        {
            this.iso_3166_alpha2_code_ = val;
            this.iso_3166_alpha2_code_selected = true;
            
            this.x121_dcc_code_selected = false;
            
            this.iso_3166_alpha2_code_selected = false;
            
        }
  

        public void initWithDefaults()
        {
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(CountryNameChoiceType));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
                
		[ASN1Element(Name = "CountryName", IsOptional = false, HasTag = true, Tag = 1, IsImplicitTag = false, TagClass = TagClasses.Application, HasDefaultValue = false)]
        public CountryNameChoiceType Value
        {
            get { return val; }
            
            set { val = value; }
            
        }

        
        
        public CountryName ()
        {
        }

        public void initWithDefaults()
        {
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(CountryName));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
