
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace ePassport {


    [ASN1PreparedElement]
    [ASN1Choice(Name = "Name")]
    public class Name : IASN1PreparedElement 
    {
        
        private RDNSequence rdnSequence_;
        private bool  rdnSequence_selected = false;

        
		[ASN1Element(Name = "rdnSequence", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public RDNSequence RdnSequence
        {
            get { return rdnSequence_; }
            set { selectRdnSequence(value); }
        }
  
        public bool isRdnSequenceSelected()
        {
            return this.rdnSequence_selected;
        }

        

        public void selectRdnSequence (RDNSequence val) 
        {
            this.rdnSequence_ = val;
            this.rdnSequence_selected = true;
            
        }
  

        public void initWithDefaults()
        {
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(Name));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
