
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace ePassport {


    [ASN1PreparedElement]
    [ASN1Sequence(Name = "ORAddress", IsSet = false)]
    public class ORAddress : IASN1PreparedElement 
    {
        
        private BuiltInStandardAttributes built_in_standard_attributes_;
        
		[ASN1Element(Name = "built-in-standard-attributes", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public BuiltInStandardAttributes Built_in_standard_attributes
        {
            get { return built_in_standard_attributes_; }
            set { built_in_standard_attributes_ = value;  }
        }
  
        private BuiltInDomainDefinedAttributes built_in_domain_defined_attributes_;
        
        private bool  built_in_domain_defined_attributes_present = false;
        
		[ASN1Element(Name = "built-in-domain-defined-attributes", IsOptional = true, HasTag = false, HasDefaultValue = false)]
        public BuiltInDomainDefinedAttributes Built_in_domain_defined_attributes
        {
            get { return built_in_domain_defined_attributes_; }
            set { built_in_domain_defined_attributes_ = value; built_in_domain_defined_attributes_present = true;  }
        }
  
        private ExtensionAttributes extension_attributes_;
        
        private bool  extension_attributes_present = false;
        
		[ASN1Element(Name = "extension-attributes", IsOptional = true, HasTag = false, HasDefaultValue = false)]
        public ExtensionAttributes Extension_attributes
        {
            get { return extension_attributes_; }
            set { extension_attributes_ = value; extension_attributes_present = true;  }
        }
  
        public bool isBuilt_in_domain_defined_attributesPresent()
        {
            return this.built_in_domain_defined_attributes_present == true;
        }
        
        public bool isExtension_attributesPresent()
        {
            return this.extension_attributes_present == true;
        }
        

        public void initWithDefaults() 
        {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(ORAddress));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
