
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace ePassport {


    [ASN1PreparedElement]
    [ASN1Choice(Name = "PostalCode")]
    public class PostalCode : IASN1PreparedElement 
    {
        
        private string numeric_code_;
        private bool  numeric_code_selected = false;

        
		[ASN1String(Name = "", StringType = UniversalTags.NumericString, IsUCS = false)]
		[ASN1ValueRangeConstraint(Min = 1, Max = 16)]
		[ASN1Element(Name = "numeric-code", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public string Numeric_code
        {
            get { return numeric_code_; }
            set { selectNumeric_code(value); }
        }
  
        private string printable_code_;
        private bool  printable_code_selected = false;

        
		[ASN1String(Name = "", StringType = UniversalTags.PrintableString, IsUCS = false)]
		[ASN1ValueRangeConstraint(Min = 1, Max = 16)]
		[ASN1Element(Name = "printable-code", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public string Printable_code
        {
            get { return printable_code_; }
            set { selectPrintable_code(value); }
        }
  
        public bool isNumeric_codeSelected()
        {
            return this.numeric_code_selected;
        }

        

        public void selectNumeric_code (string val) 
        {
            this.numeric_code_ = val;
            this.numeric_code_selected = true;
            
            this.numeric_code_selected = false;
            
            this.printable_code_selected = false;
            
        }
  
        public bool isPrintable_codeSelected()
        {
            return this.printable_code_selected;
        }

        

        public void selectPrintable_code (string val) 
        {
            this.printable_code_ = val;
            this.printable_code_selected = true;
            
            this.numeric_code_selected = false;
            
            this.printable_code_selected = false;
            
        }
  

        public void initWithDefaults()
        {
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(PostalCode));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
