
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace ePassport {


    [ASN1PreparedElement]
    [ASN1Sequence(Name = "SubjectPublicKeyInfo", IsSet = false)]
    public class SubjectPublicKeyInfo : IASN1PreparedElement 
    {
        
        private AlgorithmIdentifier algorithm_;
        
		[ASN1Element(Name = "algorithm", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public AlgorithmIdentifier Algorithm
        {
            get { return algorithm_; }
            set { algorithm_ = value;  }
        }
  
        private BitString subjectPublicKey_;
        [ASN1BitString( Name = "" )]
    
		[ASN1Element(Name = "subjectPublicKey", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public BitString SubjectPublicKey
        {
            get { return subjectPublicKey_; }
            set { subjectPublicKey_ = value;  }
        }
  

        public void initWithDefaults() 
        {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(SubjectPublicKeyInfo));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
