
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace ePassport {


    [ASN1PreparedElement]
    [ASN1Sequence(Name = "Validity", IsSet = false)]
    public class Validity : IASN1PreparedElement 
    {
        
        private Time notBefore_;
        
		[ASN1Element(Name = "notBefore", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public Time NotBefore
        {
            get { return notBefore_; }
            set { notBefore_ = value;  }
        }
  
        private Time notAfter_;
        
		[ASN1Element(Name = "notAfter", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public Time NotAfter
        {
            get { return notAfter_; }
            set { notAfter_ = value;  }
        }
  

        public void initWithDefaults() 
        {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(Validity));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
