
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace ePassport {


    [ASN1PreparedElement]
    [ASN1Choice(Name = "X520OrganizationName")]
    public class X520OrganizationName : IASN1PreparedElement 
    {
        
        private string teletexString_;
        private bool  teletexString_selected = false;

        
		[ASN1String(Name = "", StringType = UniversalTags.TeletexString, IsUCS = false)]
		[ASN1ValueRangeConstraint(Min = 1, Max = 64)]
		[ASN1Element(Name = "teletexString", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public string TeletexString
        {
            get { return teletexString_; }
            set { selectTeletexString(value); }
        }
  
        private string printableString_;
        private bool  printableString_selected = false;

        
		[ASN1String(Name = "", StringType = UniversalTags.PrintableString, IsUCS = false)]
		[ASN1ValueRangeConstraint(Min = 1, Max = 64)]
		[ASN1Element(Name = "printableString", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public string PrintableString
        {
            get { return printableString_; }
            set { selectPrintableString(value); }
        }
  
        private string universalString_;
        private bool  universalString_selected = false;

        
		[ASN1String(Name = "", StringType = UniversalTags.UniversalString, IsUCS = false)]
		[ASN1ValueRangeConstraint(Min = 1, Max = 64)]
		[ASN1Element(Name = "universalString", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public string UniversalString
        {
            get { return universalString_; }
            set { selectUniversalString(value); }
        }
  
        private string utf8String_;
        private bool  utf8String_selected = false;

        
		[ASN1String(Name = "", StringType = UniversalTags.UTF8String, IsUCS = false)]
		[ASN1ValueRangeConstraint(Min = 1, Max = 64)]
		[ASN1Element(Name = "utf8String", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public string Utf8String
        {
            get { return utf8String_; }
            set { selectUtf8String(value); }
        }
  
        private string bmpString_;
        private bool  bmpString_selected = false;

        
		[ASN1String(Name = "", StringType = UniversalTags.BMPString, IsUCS = false)]
		[ASN1ValueRangeConstraint(Min = 1, Max = 64)]
		[ASN1Element(Name = "bmpString", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public string BmpString
        {
            get { return bmpString_; }
            set { selectBmpString(value); }
        }
  
        public bool isTeletexStringSelected()
        {
            return this.teletexString_selected;
        }

        

        public void selectTeletexString (string val) 
        {
            this.teletexString_ = val;
            this.teletexString_selected = true;
            
            this.printableString_selected = false;
            
            this.universalString_selected = false;
            
            this.utf8String_selected = false;
            
            this.bmpString_selected = false;
            
        }
  
        public bool isPrintableStringSelected()
        {
            return this.printableString_selected;
        }

        

        public void selectPrintableString (string val) 
        {
            this.printableString_ = val;
            this.printableString_selected = true;
            
            this.teletexString_selected = false;
            
            this.universalString_selected = false;
            
            this.utf8String_selected = false;
            
            this.bmpString_selected = false;
            
        }
  
        public bool isUniversalStringSelected()
        {
            return this.universalString_selected;
        }

        

        public void selectUniversalString (string val) 
        {
            this.universalString_ = val;
            this.universalString_selected = true;
            
            this.teletexString_selected = false;
            
            this.printableString_selected = false;
            
            this.utf8String_selected = false;
            
            this.bmpString_selected = false;
            
        }
  
        public bool isUtf8StringSelected()
        {
            return this.utf8String_selected;
        }

        

        public void selectUtf8String (string val) 
        {
            this.utf8String_ = val;
            this.utf8String_selected = true;
            
            this.teletexString_selected = false;
            
            this.printableString_selected = false;
            
            this.universalString_selected = false;
            
            this.bmpString_selected = false;
            
        }
  
        public bool isBmpStringSelected()
        {
            return this.bmpString_selected;
        }

        

        public void selectBmpString (string val) 
        {
            this.bmpString_ = val;
            this.bmpString_selected = true;
            
            this.teletexString_selected = false;
            
            this.printableString_selected = false;
            
            this.universalString_selected = false;
            
            this.utf8String_selected = false;
            
        }
  

        public void initWithDefaults()
        {
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(X520OrganizationName));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
