
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace ePassport {


    [ASN1PreparedElement]
    [ASN1Sequence(Name = "ACClearAttrs", IsSet = false)]
    public class ACClearAttrs : IASN1PreparedElement 
    {
        
        private GeneralName acIssuer_;
        
		[ASN1Element(Name = "acIssuer", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public GeneralName AcIssuer
        {
            get { return acIssuer_; }
            set { acIssuer_ = value;  }
        }
  
        private BigInteger acSerial_;
        [ASN1Integer( Name = "" )]
    
		[ASN1Element(Name = "acSerial", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public BigInteger AcSerial
        {
            get { return acSerial_; }
            set { acSerial_ = value;  }
        }
  
        private System.Collections.Generic.ICollection<Attribute> attrs_;
        
		[ASN1SequenceOf(Name = "attrs", IsSetOf = false)]
    
		[ASN1Element(Name = "attrs", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public System.Collections.Generic.ICollection<Attribute> Attrs
        {
            get { return attrs_; }
            set { attrs_ = value;  }
        }
  

        public void initWithDefaults() 
        {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(ACClearAttrs));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
