
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace ePassport {


    [ASN1PreparedElement]
    [ASN1Sequence(Name = "AttCertValidityPeriod", IsSet = false)]
    public class AttCertValidityPeriod : IASN1PreparedElement 
    {
        
        private string notBeforeTime_;
        
		[ASN1String(Name = "", StringType = UniversalTags.GeneralizedTime, IsUCS = false)]
		[ASN1Element(Name = "notBeforeTime", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public string NotBeforeTime
        {
            get { return notBeforeTime_; }
            set { notBeforeTime_ = value;  }
        }
  
        private string notAfterTime_;
        
		[ASN1String(Name = "", StringType = UniversalTags.GeneralizedTime, IsUCS = false)]
		[ASN1Element(Name = "notAfterTime", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public string NotAfterTime
        {
            get { return notAfterTime_; }
            set { notAfterTime_ = value;  }
        }
  

        public void initWithDefaults() 
        {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(AttCertValidityPeriod));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
