
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace ePassport {


    [ASN1PreparedElement]
    [ASN1Sequence(Name = "SvceAuthInfo", IsSet = false)]
    public class SvceAuthInfo : IASN1PreparedElement 
    {
        
        private GeneralName service_;
        
		[ASN1Element(Name = "service", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public GeneralName Service
        {
            get { return service_; }
            set { service_ = value;  }
        }
  
        private GeneralName ident_;
        
		[ASN1Element(Name = "ident", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public GeneralName Ident
        {
            get { return ident_; }
            set { ident_ = value;  }
        }
  
        private byte[] authInfo_;
        
        private bool  authInfo_present = false;
        [ASN1OctetString( Name = "" )]
    
		[ASN1Element(Name = "authInfo", IsOptional = true, HasTag = false, HasDefaultValue = false)]
        public byte[] AuthInfo
        {
            get { return authInfo_; }
            set { authInfo_ = value; authInfo_present = true;  }
        }
  
        public bool isAuthInfoPresent()
        {
            return this.authInfo_present == true;
        }
        

        public void initWithDefaults() 
        {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(SvceAuthInfo));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
