
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace ePassport {


    [ASN1PreparedElement]
    [ASN1Sequence(Name = "AccessDescription", IsSet = false)]
    public class AccessDescription : IASN1PreparedElement 
    {
        
        private ObjectIdentifier accessMethod_;
        [ASN1ObjectIdentifier( Name = "" )]
    
		[ASN1Element(Name = "accessMethod", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public ObjectIdentifier AccessMethod
        {
            get { return accessMethod_; }
            set { accessMethod_ = value;  }
        }
  
        private GeneralName accessLocation_;
        
		[ASN1Element(Name = "accessLocation", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public GeneralName AccessLocation
        {
            get { return accessLocation_; }
            set { accessLocation_ = value;  }
        }
  

        public void initWithDefaults() 
        {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(AccessDescription));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
