
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace ePassport {


    [ASN1PreparedElement]
    [ASN1BoxedType(Name = "BaseDistance")]
    public class BaseDistance: IASN1PreparedElement 
    {
    
        private long val;
        
        [ASN1Integer(Name = "BaseDistance")]
        
		[ASN1ValueRangeConstraint(Min = 0, Max = long.MaxValue)]
        public long Value
        {
            get { return val; }
            set { val = value; }
        }
        
        public BaseDistance()
        {
        }

        public BaseDistance(long value)
        {
            this.Value = value;
        }

        public void initWithDefaults()
        {
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(BaseDistance));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
