
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace ePassport {


    [ASN1PreparedElement]
    [ASN1Choice(Name = "GeneralName")]
    public class GeneralName : IASN1PreparedElement 
    {
        
        private AnotherName otherName_;
        private bool  otherName_selected = false;

        
		[ASN1Element(Name = "otherName", IsOptional = false, HasTag = true, Tag = 0, HasDefaultValue = false)]
        public AnotherName OtherName
        {
            get { return otherName_; }
            set { selectOtherName(value); }
        }
  
        private string rfc822Name_;
        private bool  rfc822Name_selected = false;

        
		[ASN1String(Name = "", StringType = UniversalTags.IA5String, IsUCS = false)]
		[ASN1Element(Name = "rfc822Name", IsOptional = false, HasTag = true, Tag = 1, HasDefaultValue = false)]
        public string Rfc822Name
        {
            get { return rfc822Name_; }
            set { selectRfc822Name(value); }
        }
  
        private string dNSName_;
        private bool  dNSName_selected = false;

        
		[ASN1String(Name = "", StringType = UniversalTags.IA5String, IsUCS = false)]
		[ASN1Element(Name = "dNSName", IsOptional = false, HasTag = true, Tag = 2, HasDefaultValue = false)]
        public string DNSName
        {
            get { return dNSName_; }
            set { selectDNSName(value); }
        }
  
        private ORAddress x400Address_;
        private bool  x400Address_selected = false;

        
		[ASN1Element(Name = "x400Address", IsOptional = false, HasTag = true, Tag = 3, HasDefaultValue = false)]
        public ORAddress X400Address
        {
            get { return x400Address_; }
            set { selectX400Address(value); }
        }
  
        private Name directoryName_;
        private bool  directoryName_selected = false;

        
		[ASN1Element(Name = "directoryName", IsOptional = false, HasTag = true, Tag = 4, HasDefaultValue = false)]
        public Name DirectoryName
        {
            get { return directoryName_; }
            set { selectDirectoryName(value); }
        }
  
        private EDIPartyName ediPartyName_;
        private bool  ediPartyName_selected = false;

        
		[ASN1Element(Name = "ediPartyName", IsOptional = false, HasTag = true, Tag = 5, HasDefaultValue = false)]
        public EDIPartyName EdiPartyName
        {
            get { return ediPartyName_; }
            set { selectEdiPartyName(value); }
        }
  
        private string uniformResourceIdentifier_;
        private bool  uniformResourceIdentifier_selected = false;

        
		[ASN1String(Name = "", StringType = UniversalTags.IA5String, IsUCS = false)]
		[ASN1Element(Name = "uniformResourceIdentifier", IsOptional = false, HasTag = true, Tag = 6, HasDefaultValue = false)]
        public string UniformResourceIdentifier
        {
            get { return uniformResourceIdentifier_; }
            set { selectUniformResourceIdentifier(value); }
        }
  
        private byte[] iPAddress_;
        private bool  iPAddress_selected = false;

        [ASN1OctetString( Name = "" )]
    
		[ASN1Element(Name = "iPAddress", IsOptional = false, HasTag = true, Tag = 7, HasDefaultValue = false)]
        public byte[] IPAddress
        {
            get { return iPAddress_; }
            set { selectIPAddress(value); }
        }
  
        private ObjectIdentifier registeredID_;
        private bool  registeredID_selected = false;

        [ASN1ObjectIdentifier( Name = "" )]
    
		[ASN1Element(Name = "registeredID", IsOptional = false, HasTag = true, Tag = 8, HasDefaultValue = false)]
        public ObjectIdentifier RegisteredID
        {
            get { return registeredID_; }
            set { selectRegisteredID(value); }
        }
  
        public bool isOtherNameSelected()
        {
            return this.otherName_selected;
        }

        

        public void selectOtherName (AnotherName val) 
        {
            this.otherName_ = val;
            this.otherName_selected = true;
            
            this.rfc822Name_selected = false;
            
            this.dNSName_selected = false;
            
            this.x400Address_selected = false;
            
            this.directoryName_selected = false;
            
            this.ediPartyName_selected = false;
            
            this.uniformResourceIdentifier_selected = false;
            
            this.iPAddress_selected = false;
            
            this.registeredID_selected = false;
            
        }
  
        public bool isRfc822NameSelected()
        {
            return this.rfc822Name_selected;
        }

        

        public void selectRfc822Name (string val) 
        {
            this.rfc822Name_ = val;
            this.rfc822Name_selected = true;
            
            this.otherName_selected = false;
            
            this.dNSName_selected = false;
            
            this.x400Address_selected = false;
            
            this.directoryName_selected = false;
            
            this.ediPartyName_selected = false;
            
            this.uniformResourceIdentifier_selected = false;
            
            this.iPAddress_selected = false;
            
            this.registeredID_selected = false;
            
        }
  
        public bool isDNSNameSelected()
        {
            return this.dNSName_selected;
        }

        

        public void selectDNSName (string val) 
        {
            this.dNSName_ = val;
            this.dNSName_selected = true;
            
            this.otherName_selected = false;
            
            this.rfc822Name_selected = false;
            
            this.x400Address_selected = false;
            
            this.directoryName_selected = false;
            
            this.ediPartyName_selected = false;
            
            this.uniformResourceIdentifier_selected = false;
            
            this.iPAddress_selected = false;
            
            this.registeredID_selected = false;
            
        }
  
        public bool isX400AddressSelected()
        {
            return this.x400Address_selected;
        }

        

        public void selectX400Address (ORAddress val) 
        {
            this.x400Address_ = val;
            this.x400Address_selected = true;
            
            this.otherName_selected = false;
            
            this.rfc822Name_selected = false;
            
            this.dNSName_selected = false;
            
            this.directoryName_selected = false;
            
            this.ediPartyName_selected = false;
            
            this.uniformResourceIdentifier_selected = false;
            
            this.iPAddress_selected = false;
            
            this.registeredID_selected = false;
            
        }
  
        public bool isDirectoryNameSelected()
        {
            return this.directoryName_selected;
        }

        

        public void selectDirectoryName (Name val) 
        {
            this.directoryName_ = val;
            this.directoryName_selected = true;
            
            this.otherName_selected = false;
            
            this.rfc822Name_selected = false;
            
            this.dNSName_selected = false;
            
            this.x400Address_selected = false;
            
            this.ediPartyName_selected = false;
            
            this.uniformResourceIdentifier_selected = false;
            
            this.iPAddress_selected = false;
            
            this.registeredID_selected = false;
            
        }
  
        public bool isEdiPartyNameSelected()
        {
            return this.ediPartyName_selected;
        }

        

        public void selectEdiPartyName (EDIPartyName val) 
        {
            this.ediPartyName_ = val;
            this.ediPartyName_selected = true;
            
            this.otherName_selected = false;
            
            this.rfc822Name_selected = false;
            
            this.dNSName_selected = false;
            
            this.x400Address_selected = false;
            
            this.directoryName_selected = false;
            
            this.uniformResourceIdentifier_selected = false;
            
            this.iPAddress_selected = false;
            
            this.registeredID_selected = false;
            
        }
  
        public bool isUniformResourceIdentifierSelected()
        {
            return this.uniformResourceIdentifier_selected;
        }

        

        public void selectUniformResourceIdentifier (string val) 
        {
            this.uniformResourceIdentifier_ = val;
            this.uniformResourceIdentifier_selected = true;
            
            this.otherName_selected = false;
            
            this.rfc822Name_selected = false;
            
            this.dNSName_selected = false;
            
            this.x400Address_selected = false;
            
            this.directoryName_selected = false;
            
            this.ediPartyName_selected = false;
            
            this.iPAddress_selected = false;
            
            this.registeredID_selected = false;
            
        }
  
        public bool isIPAddressSelected()
        {
            return this.iPAddress_selected;
        }

        

        public void selectIPAddress (byte[] val) 
        {
            this.iPAddress_ = val;
            this.iPAddress_selected = true;
            
            this.otherName_selected = false;
            
            this.rfc822Name_selected = false;
            
            this.dNSName_selected = false;
            
            this.x400Address_selected = false;
            
            this.directoryName_selected = false;
            
            this.ediPartyName_selected = false;
            
            this.uniformResourceIdentifier_selected = false;
            
            this.registeredID_selected = false;
            
        }
  
        public bool isRegisteredIDSelected()
        {
            return this.registeredID_selected;
        }

        

        public void selectRegisteredID (ObjectIdentifier val) 
        {
            this.registeredID_ = val;
            this.registeredID_selected = true;
            
            this.otherName_selected = false;
            
            this.rfc822Name_selected = false;
            
            this.dNSName_selected = false;
            
            this.x400Address_selected = false;
            
            this.directoryName_selected = false;
            
            this.ediPartyName_selected = false;
            
            this.uniformResourceIdentifier_selected = false;
            
            this.iPAddress_selected = false;
            
        }
  

        public void initWithDefaults()
        {
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(GeneralName));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
