
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace ePassport {


    [ASN1PreparedElement]
    [ASN1Sequence(Name = "PolicyQualifierInfo", IsSet = false)]
    public class PolicyQualifierInfo : IASN1PreparedElement 
    {
        
        private PolicyQualifierId policyQualifierId_;
        
		[ASN1Element(Name = "policyQualifierId", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public PolicyQualifierId PolicyQualifierId
        {
            get { return policyQualifierId_; }
            set { policyQualifierId_ = value;  }
        }
  
        private byte[] qualifier_;
        [ASN1Any( Name = "" )]
    
		[ASN1Element(Name = "qualifier", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public byte[] Qualifier
        {
            get { return qualifier_; }
            set { qualifier_ = value;  }
        }
  

        public void initWithDefaults() 
        {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(PolicyQualifierInfo));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
