
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace ePassport {


    [ASN1PreparedElement]
    [ASN1BoxedType(Name = "PolicyMappings")]
    public class PolicyMappings : IASN1PreparedElement 
    {

        private System.Collections.Generic.ICollection<PolicyMappingsSequenceType> val = null; 
        
        
    [ASN1PreparedElement]
    [ASN1Sequence(Name = "PolicyMappings", IsSet = false)]
    public class PolicyMappingsSequenceType : IASN1PreparedElement
    {
        
        private CertPolicyId issuerDomainPolicy_;
        
		[ASN1Element(Name = "issuerDomainPolicy", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public CertPolicyId IssuerDomainPolicy
        {
            get { return issuerDomainPolicy_; }
            set { issuerDomainPolicy_ = value;  }
        }
  
        private CertPolicyId subjectDomainPolicy_;
        
		[ASN1Element(Name = "subjectDomainPolicy", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public CertPolicyId SubjectDomainPolicy
        {
            get { return subjectDomainPolicy_; }
            set { subjectDomainPolicy_ = value;  }
        }
  
        
        public void initWithDefaults() 
        {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(PolicyMappingsSequenceType));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }
    }
                
		[ASN1ValueRangeConstraint(Min = 1, Max = long.MaxValue)]
        [ASN1SequenceOf(Name = "PolicyMappings", IsSetOf = false)]

        public System.Collections.Generic.ICollection<PolicyMappingsSequenceType> Value
        {
            get { return val; }
            set { val = value; }
        }
        
        public void initValue() 
        {
            this.Value = new System.Collections.Generic.List<PolicyMappingsSequenceType>();
        }
        
        public void Add(PolicyMappingsSequenceType item) 
        {
            this.Value.Add(item);
        }

        public void initWithDefaults()
        {
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(PolicyMappings));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
