
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace ePassport {


    [ASN1PreparedElement]
    [ASN1Sequence(Name = "Dss_Parms", IsSet = false)]
    public class Dss_Parms : IASN1PreparedElement 
    {
        
        private BigInteger p_;
        [ASN1Integer( Name = "" )]
    
		[ASN1Element(Name = "p", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public BigInteger P
        {
            get { return p_; }
            set { p_ = value;  }
        }
  
        private BigInteger q_;
        [ASN1Integer( Name = "" )]
    
		[ASN1Element(Name = "q", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public BigInteger Q
        {
            get { return q_; }
            set { q_ = value;  }
        }
  
        private BigInteger g_;
        [ASN1Integer( Name = "" )]
    
		[ASN1Element(Name = "g", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public BigInteger G
        {
            get { return g_; }
            set { g_ = value;  }
        }
  

        public void initWithDefaults() 
        {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(Dss_Parms));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
