
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace ePassport {


    [ASN1PreparedElement]
    [ASN1Sequence(Name = "Dss_Sig_Value", IsSet = false)]
    public class Dss_Sig_Value : IASN1PreparedElement 
    {
        
        private BigInteger r_;
        [ASN1Integer( Name = "" )]
    
		[ASN1Element(Name = "r", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public BigInteger R
        {
            get { return r_; }
            set { r_ = value;  }
        }
  
        private BigInteger s_;
        [ASN1Integer( Name = "" )]
    
		[ASN1Element(Name = "s", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public BigInteger S
        {
            get { return s_; }
            set { s_ = value;  }
        }
  

        public void initWithDefaults() 
        {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(Dss_Sig_Value));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
