
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace ePassport {


    [ASN1PreparedElement]
    [ASN1Sequence(Name = "RC2CBCParameter", IsSet = false)]
    public class RC2CBCParameter : IASN1PreparedElement 
    {
        
        private BigInteger rc2ParameterVersion_;
        [ASN1Integer( Name = "" )]
    
		[ASN1Element(Name = "rc2ParameterVersion", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public BigInteger Rc2ParameterVersion
        {
            get { return rc2ParameterVersion_; }
            set { rc2ParameterVersion_ = value;  }
        }
  
        private byte[] iv_;
        [ASN1OctetString( Name = "" )]
    
		[ASN1Element(Name = "iv", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public byte[] Iv
        {
            get { return iv_; }
            set { iv_ = value;  }
        }
  

        public void initWithDefaults() 
        {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(RC2CBCParameter));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
