
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace ePassport {


    [ASN1PreparedElement]
    [ASN1Sequence(Name = "ValidationParms", IsSet = false)]
    public class ValidationParms : IASN1PreparedElement 
    {
        
        private BitString seed_;
        [ASN1BitString( Name = "" )]
    
		[ASN1Element(Name = "seed", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public BitString Seed
        {
            get { return seed_; }
            set { seed_ = value;  }
        }
  
        private BigInteger pgenCounter_;
        [ASN1Integer( Name = "" )]
    
		[ASN1Element(Name = "pgenCounter", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public BigInteger PgenCounter
        {
            get { return pgenCounter_; }
            set { pgenCounter_ = value;  }
        }
  

        public void initWithDefaults() 
        {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(ValidationParms));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
