
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace ePassport {


    [ASN1PreparedElement]
    [ASN1BoxedType(Name = "DG1")]
    public class DG1: IASN1PreparedElement 
    {

        private DG1SequenceType val;

        
    [ASN1PreparedElement]
    [ASN1Sequence(Name = "DG1", IsSet = false)]
    public class DG1SequenceType : IASN1PreparedElement
    {
        
        private string mrz_;
        
		[ASN1String(Name = "", StringType = UniversalTags.IA5String, IsUCS = false)]
		[ASN1Element(Name = "mrz", IsOptional = false, HasTag = true, Tag = 31, TagClass = TagClasses.Application, HasDefaultValue = false)]
        public string Mrz
        {
            get { return mrz_; }
            set { mrz_ = value;  }
        }
  
        
        public void initWithDefaults() 
        {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(DG1SequenceType));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }
    }
                
		[ASN1Element(Name = "DG1", IsOptional = false, HasTag = true, Tag = 1, TagClass = TagClasses.Application, HasDefaultValue = false)]
        public DG1SequenceType Value
        {
            get { return val; }
            
            set { val = value; }
            
        }

        
        
        public DG1 ()
        {
        }

        public void initWithDefaults()
        {
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(DG1));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
