
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace ePassport {


    [ASN1PreparedElement]
    [ASN1BoxedType(Name = "DG14")]
    public class DG14: IASN1PreparedElement 
    {

        private DG14SequenceType val;

        
    [ASN1PreparedElement]
    [ASN1Sequence(Name = "DG14", IsSet = false)]
    public class DG14SequenceType : IASN1PreparedElement
    {
        
        private SecurityInfos securityInfos_;
        
		[ASN1Element(Name = "securityInfos", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public SecurityInfos SecurityInfos
        {
            get { return securityInfos_; }
            set { securityInfos_ = value;  }
        }
  
        
        public void initWithDefaults() 
        {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(DG14SequenceType));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }
    }
                
		[ASN1Element(Name = "DG14", IsOptional = false, HasTag = true, Tag = 14, TagClass = TagClasses.Application, HasDefaultValue = false)]
        public DG14SequenceType Value
        {
            get { return val; }
            
            set { val = value; }
            
        }

        
        
        public DG14 ()
        {
        }

        public void initWithDefaults()
        {
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(DG14));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
