
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace ePassport {


    [ASN1PreparedElement]
    [ASN1BoxedType(Name = "DG15")]
    public class DG15: IASN1PreparedElement 
    {

        private DG15SequenceType val;

        
    [ASN1PreparedElement]
    [ASN1Sequence(Name = "DG15", IsSet = false)]
    public class DG15SequenceType : IASN1PreparedElement
    {
        
        private ActiveAuthenticationPublicKeyInfo activeAuthenticationPublicKeyInfo_;
        
		[ASN1Element(Name = "activeAuthenticationPublicKeyInfo", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public ActiveAuthenticationPublicKeyInfo ActiveAuthenticationPublicKeyInfo
        {
            get { return activeAuthenticationPublicKeyInfo_; }
            set { activeAuthenticationPublicKeyInfo_ = value;  }
        }
  
        
        public void initWithDefaults() 
        {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(DG15SequenceType));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }
    }
                
		[ASN1Element(Name = "DG15", IsOptional = false, HasTag = true, Tag = 15, TagClass = TagClasses.Application, HasDefaultValue = false)]
        public DG15SequenceType Value
        {
            get { return val; }
            
            set { val = value; }
            
        }

        
        
        public DG15 ()
        {
        }

        public void initWithDefaults()
        {
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(DG15));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
