
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace ePassport {


    [ASN1PreparedElement]
    [ASN1Sequence(Name = "SecurityInfo", IsSet = false)]
    public class SecurityInfo : IASN1PreparedElement 
    {
        
        private ObjectIdentifier protocol_;
        [ASN1ObjectIdentifier( Name = "" )]
    
		[ASN1Element(Name = "protocol", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public ObjectIdentifier Protocol
        {
            get { return protocol_; }
            set { protocol_ = value;  }
        }
  
        private byte[] requiredData_;
        [ASN1Any( Name = "" )]
    
		[ASN1Element(Name = "requiredData", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public byte[] RequiredData
        {
            get { return requiredData_; }
            set { requiredData_ = value;  }
        }
  
        private byte[] optionalData_;
        
        private bool  optionalData_present = false;
        [ASN1Any( Name = "" )]
    
		[ASN1Element(Name = "optionalData", IsOptional = true, HasTag = false, HasDefaultValue = false)]
        public byte[] OptionalData
        {
            get { return optionalData_; }
            set { optionalData_ = value; optionalData_present = true;  }
        }
  
        public bool isOptionalDataPresent()
        {
            return this.optionalData_present == true;
        }
        

        public void initWithDefaults() 
        {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(SecurityInfo));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
