
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace ePassport {


    [ASN1PreparedElement]
    [ASN1Sequence(Name = "SodContentInfo", IsSet = false)]
    public class SodContentInfo : IASN1PreparedElement 
    {
        
        private ObjectIdentifier oid_;
        [ASN1ObjectIdentifier( Name = "" )]
    
		[ASN1Element(Name = "oid", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public ObjectIdentifier Oid
        {
            get { return oid_; }
            set { oid_ = value;  }
        }
  
        private SignedData signedData_;
        
		[ASN1Element(Name = "signedData", IsOptional = false, HasTag = true, Tag = 0, IsImplicitTag = false, HasDefaultValue = false)]
        public SignedData SignedData
        {
            get { return signedData_; }
            set { signedData_ = value;  }
        }
  

        public void initWithDefaults() 
        {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(SodContentInfo));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
