
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace ePassport {


    [ASN1PreparedElement]
    [ASN1Sequence(Name = "Characteristic_two", IsSet = false)]
    public class Characteristic_two : IASN1PreparedElement 
    {
        
        private BigInteger m_;
        [ASN1Integer( Name = "" )]
    
		[ASN1Element(Name = "m", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public BigInteger M
        {
            get { return m_; }
            set { m_ = value;  }
        }
  
        private ObjectIdentifier basis_;
        [ASN1ObjectIdentifier( Name = "" )]
    
		[ASN1Element(Name = "basis", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public ObjectIdentifier Basis
        {
            get { return basis_; }
            set { basis_ = value;  }
        }
  
        private byte[] parameters_;
        [ASN1Any( Name = "" )]
    
		[ASN1Element(Name = "parameters", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public byte[] Parameters
        {
            get { return parameters_; }
            set { parameters_ = value;  }
        }
  

        public void initWithDefaults() 
        {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(Characteristic_two));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
