
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace ePassport {


    [ASN1PreparedElement]
    [ASN1Choice(Name = "EcpkParameters")]
    public class EcpkParameters : IASN1PreparedElement 
    {
        
        private ECParameters ecParameters_;
        private bool  ecParameters_selected = false;

        
		[ASN1Element(Name = "ecParameters", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public ECParameters EcParameters
        {
            get { return ecParameters_; }
            set { selectEcParameters(value); }
        }
  
        private ObjectIdentifier namedCurve_;
        private bool  namedCurve_selected = false;

        [ASN1ObjectIdentifier( Name = "" )]
    
		[ASN1Element(Name = "namedCurve", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public ObjectIdentifier NamedCurve
        {
            get { return namedCurve_; }
            set { selectNamedCurve(value); }
        }
  
        private NullObject implicitlyCA_;
        private bool  implicitlyCA_selected = false;

        
        [ASN1Null ( Name = "implicitlyCA" )]
    
		[ASN1Element(Name = "implicitlyCA", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public NullObject ImplicitlyCA
        {
            get { return implicitlyCA_; }
            set { selectImplicitlyCA(value); }
        }
  
        public bool isEcParametersSelected()
        {
            return this.ecParameters_selected;
        }

        

        public void selectEcParameters (ECParameters val) 
        {
            this.ecParameters_ = val;
            this.ecParameters_selected = true;
            
            this.namedCurve_selected = false;
            
            this.implicitlyCA_selected = false;
            
        }
  
        public bool isNamedCurveSelected()
        {
            return this.namedCurve_selected;
        }

        

        public void selectNamedCurve (ObjectIdentifier val) 
        {
            this.namedCurve_ = val;
            this.namedCurve_selected = true;
            
            this.ecParameters_selected = false;
            
            this.implicitlyCA_selected = false;
            
        }
  
        public bool isImplicitlyCASelected()
        {
            return this.implicitlyCA_selected;
        }

        
        public void selectImplicitlyCA() 
        {
            selectImplicitlyCA (new NullObject());
        }
        

        public void selectImplicitlyCA (NullObject val) 
        {
            this.implicitlyCA_ = val;
            this.implicitlyCA_selected = true;
            
            this.ecParameters_selected = false;
            
            this.namedCurve_selected = false;
            
        }
  

        public void initWithDefaults()
        {
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(EcpkParameters));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
