
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace ePassport {


    [ASN1PreparedElement]
    [ASN1Sequence(Name = "Pentanomial", IsSet = false)]
    public class Pentanomial : IASN1PreparedElement 
    {
        
        private BigInteger k1_;
        [ASN1Integer( Name = "" )]
    
		[ASN1Element(Name = "k1", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public BigInteger K1
        {
            get { return k1_; }
            set { k1_ = value;  }
        }
  
        private BigInteger k2_;
        [ASN1Integer( Name = "" )]
    
		[ASN1Element(Name = "k2", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public BigInteger K2
        {
            get { return k2_; }
            set { k2_ = value;  }
        }
  
        private BigInteger k3_;
        [ASN1Integer( Name = "" )]
    
		[ASN1Element(Name = "k3", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public BigInteger K3
        {
            get { return k3_; }
            set { k3_ = value;  }
        }
  

        public void initWithDefaults() 
        {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(Pentanomial));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
