
//
// This file was generated by the BinaryNotes compiler (created by Abdulla Abdurakhmanov, modified by Sylvain Prevost).
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using System.Numerics;

using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace ePassport {


    [ASN1PreparedElement]
    [ASN1Sequence(Name = "RSAPublicKey", IsSet = false)]
    public class RSAPublicKey : IASN1PreparedElement 
    {
        
        private BigInteger modulus_;
        [ASN1Integer( Name = "" )]
    
		[ASN1Element(Name = "modulus", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public BigInteger Modulus
        {
            get { return modulus_; }
            set { modulus_ = value;  }
        }
  
        private BigInteger publicExponent_;
        [ASN1Integer( Name = "" )]
    
		[ASN1Element(Name = "publicExponent", IsOptional = false, HasTag = false, HasDefaultValue = false)]
        public BigInteger PublicExponent
        {
            get { return publicExponent_; }
            set { publicExponent_ = value;  }
        }
  

        public void initWithDefaults() 
        {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(RSAPublicKey));
        public IASN1PreparedElementData PreparedData 
        {
            get { return preparedData; }
        }

    }
            
}
